//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentId { get; set; }
        public int orderId { get; set; }
        public string paymentMethod { get; set; }
        public string paymentStatus { get; set; }
        public string transactionId { get; set; }
        public decimal paidAmount { get; set; }
        public Nullable<System.DateTime> paidDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
