//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int shipmentId { get; set; }
        public int orderId { get; set; }
        public string trackingNumber { get; set; }
        public string carrier { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> estimatedDelivery { get; set; }
        public Nullable<System.DateTime> deliveredDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
